spring.application.name=users
server.port=8071

spring.profiles.active=docker
spring.config.import=configserver:http://configserver:8072/

management.endpoints.web.exposure.include=*
management.endpoint.shutdown.access=unrestricted

eureka.instance.prefer-ip-address=true
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=http://eurekaserver:8074/eureka/

info.app.name=users
info.app.description=users service
info.app.version=0.0.1